apiVersion: apps/v1
kind: Deployment
metadata:
  name: filesure-api
  namespace: filesure-prod
  labels:
    app: filesure-api
    monitor: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: filesure-api
  template:
    metadata:
      labels:
        app: filesure-api
        monitor: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: filesure-api
        image: filesureacr.azurecr.io/filesure-api:latest
        ports:
        - containerPort: 5001
          name: http
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: filesure-secrets
              key: MONGO_URI
        - name: AZURE_BLOB_CONN
          valueFrom:
            secretKeyRef:
              name: filesure-secrets
              key: AZURE_BLOB_CONN
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: filesure-api
  namespace: filesure-prod
  labels:
    app: filesure-api
spec:
  selector:
    app: filesure-api
  ports:
  - port: 80
    targetPort: 5001
    name: http
  type: LoadBalancer

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: filesure-api-monitor
  namespace: filesure-prod
spec:
  selector:
    matchLabels:
      app: filesure-api
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
