apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: filesure-worker-scaledjob
  namespace: filesure-prod
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: filesure-worker
      spec:
        containers:
          - name: filesure-worker
            image: filesureacr.azurecr.io/filesure-worker:latest
            imagePullPolicy: Always
            command: ["./start-worker.sh"]
            env:
              - name: MONGO_URI
                valueFrom:
                  secretKeyRef:
                    name: filesure-secrets
                    key: MONGO_URI
              - name: MONGO_URI_STANDARD  # ADD THIS for KEDA
                valueFrom:
                  secretKeyRef:
                    name: filesure-secrets
                    key: MONGO_URI_STANDARD
              - name: AZURE_BLOB_CONN
                valueFrom:
                  secretKeyRef:
                    name: filesure-secrets
                    key: AZURE_BLOB_CONN
              - name: AZURE_CONTAINER
                valueFrom:
                  secretKeyRef:
                    name: filesure-secrets
                    key: AZURE_CONTAINER
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"  # Increased for Python
              limits:
                cpu: "500m"
                memory: "512Mi"
            ports:
              - containerPort: 9100
                name: metrics
        restartPolicy: Never
  pollingInterval: 30
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  maxReplicaCount: 10
  triggers:
    - type: mongodb
      metadata:
        connectionFromEnv: MONGO_URI_STANDARD  # CHANGED: Use standard connection
        databaseName: filesure
        collectionName: jobs
        query: '{"jobStatus":"pending"}'  # CHANGED: query instead of queryValue
        queryValue: "1"                   # ADDED: target value
        activationQueryValue: "1"   

---

apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: filesure-worker-monitor
  namespace: filesure-prod
spec:
  selector:
    matchLabels:
      app: filesure-worker
  podMetricsEndpoints:
    - port: 9100
      interval: 30s
      path: /metrics
