apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: filesure-worker-scaledjob
  namespace: filesure-prod
spec:
  pollingInterval: 30
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  maxReplicaCount: 10
  jobTargetRef:
    backoffLimit: 2
    completions: 1
    ttlSecondsAfterFinished: 300
    template:
      metadata:
        labels:
          app: filesure-worker
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9100"
          prometheus.io/path: "/metrics"
      spec:
        restartPolicy: Never
        containers:
        - name: filesure-worker
          image: filesureacr.azurecr.io/filesure-worker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9100
              name: metrics
          command: ["/bin/sh", "-c"]
          args: ["python downloader.py $JOB_ID"]
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: filesure-secrets
                  key: MONGO_URI
            - name: AZURE_BLOB_CONN
              valueFrom:
                secretKeyRef:
                  name: filesure-secrets
                  key: AZURE_BLOB_CONN
            - name: AZURE_CONTAINER
              value: "documents"
            # KEDA injects queryValue (_id) into pod annotations as job_id
            - name: JOB_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['job_id']
          resources:
            requests:
              memory: "100Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
  triggers:
  - type: mongodb
    metadata:
      connectionStringFromEnv: MONGO_URI
      dbName: filesure
      collection: jobs
      query: '{"jobStatus": "pending"}'
      queryValue: "_id"     # tell KEDA to extract the document’s ObjectId (_id)
    authenticationRef:
      name: mongo-auth

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: filesure-worker-monitor
  namespace: filesure-prod
spec:
  selector:
    matchLabels:
      app: filesure-worker
  podMetricsEndpoints:
  - port: metrics
    interval: 30s
    path: /metrics
