apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: filesure-worker-scaledjob
  namespace: filesure-prod
spec:
  pollingInterval: 30
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  maxReplicaCount: 10
  jobTargetRef:
    backoffLimit: 2
    completions: 1
    ttlSecondsAfterFinished: 300
    template:
      metadata:
        labels:
          app: filesure-worker
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9100"
          prometheus.io/path: "/metrics"
      spec:
        restartPolicy: Never
        containers:
        - name: filesure-worker
          image: filesureacr.azurecr.io/filesure-worker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9100
              name: metrics
          # Use shell command to extract job ID from KEDA annotation and pass as argument
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Extract job ID from KEDA annotation
              JOB_ID=$(cat /etc/keda-annotations/job-id 2>/dev/null || echo "")
              if [ -n "$JOB_ID" ]; then
                echo "Processing job ID: $JOB_ID"
                python downloader.py "$JOB_ID"
              else
                echo "No job ID found in annotations, exiting"
                exit 1
              fi
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: filesure-secrets
                  key: MONGO_URI
            - name: AZURE_BLOB_CONN
              valueFrom:
                secretKeyRef:
                  name: filesure-secrets
                  key: AZURE_BLOB_CONN
            - name: AZURE_CONTAINER
              value: "documents"
          volumeMounts:
            - name: keda-annotations
              mountPath: /etc/keda-annotations
              readOnly: true
          resources:
            requests:
              memory: "100Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        volumes:
          - name: keda-annotations
            downwardAPI:
              items:
                - path: "job-id"
                  fieldRef:
                    fieldPath: metadata.annotations['keda.k8s.io/job-id']
  triggers:
  - type: mongodb
    metadata:
      connectionStringFromEnv: MONGO_URI
      dbName: filesure
      collection: jobs
      query: '{"jobStatus": "pending"}'
      queryValue: "1"  # Scale 1 pod per pending job
      # This tells KEDA to extract the _id field and pass it as job-id
      jobId: "_id"
    authenticationRef:
      name: mongo-auth

---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: mongo-auth
  namespace: filesure-prod
spec:
  secretTargetRef:
    - parameter: connectionString
      name: filesure-secrets
      key: MONGO_URI

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: filesure-worker-monitor
  namespace: filesure-prod
spec:
  selector:
    matchLabels:
      app: filesure-worker
  podMetricsEndpoints:
  - port: metrics
    interval: 30s
    path: "/metrics"