apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: filesure-worker-scaledjob
  namespace: filesure-prod
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: filesure-worker
      spec:
        containers:
          - name: filesure-worker
            image: filesureacr.azurecr.io/filesure-worker:latest
            imagePullPolicy: Always
            command: ["./start-worker.sh"]
            env:
              - name: MONGO_URI
                valueFrom:
                  secretKeyRef:
                    name: filesure-secrets
                    key: MONGO_URI
              - name: AZURE_BLOB_CONN
                valueFrom:
                  secretKeyRef:
                    name: filesure-secrets
                    key: AZURE_BLOB_CONN
              - name: AZURE_CONTAINER
                valueFrom:
                  secretKeyRef:
                    name: filesure-secrets
                    key: AZURE_CONTAINER
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"
        restartPolicy: Never
  pollingInterval: 30
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  maxReplicaCount: 10
  triggers:
    - type: mongodb
      metadata:
        # Correct parameter names for KEDA v2
        uriFromEnv: MONGO_URI
        dbName: filesure
        collection: jobs
        query: '{"jobStatus":"pending"}'
        targetValue: "1"

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: filesure-worker-monitor
  namespace: filesure-prod
spec:
  selector:
    matchLabels:
      app: filesure-worker
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /metrics
