name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Docker images
      run: |
        docker build -t filesureacr.azurecr.io/filesure-api:latest ./api
        docker build -t filesureacr.azurecr.io/filesure-worker:latest ./worker
        docker push filesureacr.azurecr.io/filesure-api:latest
        docker push filesureacr.azurecr.io/filesure-worker:latest

    - name: Deploy to AKS
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        AZURE_BLOB_CONN: ${{ secrets.AZURE_BLOB_CONN }}
      run: |
        # Create K8s secret from environment variables
        kubectl create secret generic filesure-secrets \
          --namespace filesure-prod \
          --from-literal=mongo-uri="$MONGO_URI" \
          --from-literal=azure-blob-conn="$AZURE_BLOB_CONN" \
          --dry-run=client -o yaml | kubectl apply -f -

        # Deploy manifests
        kubectl apply -f k8s/api-deployment.yaml
        kubectl apply -f k8s/worker-scaledjob.yaml
