name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build & Push Docker images
      run: |
        docker build -t filesureacr.azurecr.io/filesure-api:latest ./api
        docker build -t filesureacr.azurecr.io/filesure-worker:latest ./worker
        docker push filesureacr.azurecr.io/filesure-api:latest
        docker push filesureacr.azurecr.io/filesure-worker:latest

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/secrets.yaml
        kubectl apply -f k8s/api-deployment.yaml
        kubectl apply -f k8s/worker-scaledjob.yaml
